# Generated by Django 3.2.3 on 2021-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0003_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
